module.exports= function(postNumber){
	var allBlogs = [
		{
			title:"A NEW THING",
			date:"Aug 24, 2016",
			body:"<p>This might all be a mistake.</p><p>What does it mean that you're borrowing money to put where your mouth is? I feel like I'm putting myself in one of those put-up-or-shut-up type situations but it's pretty hard to discern if this is another one of my self-delusions or this is me actually grabbing the bull by the horns. Could this be another O'Henry Awards or is this me now?</p><p>I'm waging five figures that it's the latter. That must mean something. I'm unsure of myself. This feels ridiculous typing all this for public but they told me to keep a blog, so I wrote a blog.</p><p> The only thing I know is what I don't want. I worked in IT for a big company and it was okay just like staring at ceiling tiles for a hour at the doctor's office is okay. But I was a cost to the business and I felt like a cost. Even if I worked as hard and as consistent as I could it still felt ... okay. I know I don't want to be a cost, I want to be apart of creating the value. </p><p> I don't want to go back to a traditional school. That ship has sailed for me. The Tower on campus feels just as ominous now as it did my first day on campus all those years ago. And while at school I felt like I was prepping for something I wasn't apart of. I'd have to open up some really weird cans of worms to start figuring out why I was so anxious and adrift at school. All I know is that in comparison, I have thrived outside of the traditional school system and I don't want to go through that again.</p><p>So, this feels like when I talk about why I decided to enroll at a coding bootcamp or what it was that made me grab life by the balls and twist but I think that this fire that's burning in me is special and trying to frame it so as to articulate it would be a disservice to it.</p>"	
		},
		{
			title:"AN OLD THING",
			date:"Oct 05, 2099",
			body:"<p>This might all be a mistake.</p><p>What does it mean that you're borrowing money to put where your mouth is? I feel like I'm putting myself in one of those put-up-or-shut-up type situations but it's pretty hard to discern if this is another one of my self-delusions or this is me actually grabbing the bull by the horns. Could this be another O'Henry Awards or is this me now?</p><p>I'm waging five figures that it's the latter. That must mean something. I'm unsure of myself. This feels ridiculous typing all this for public but they told me to keep a blog, so I wrote a blog.</p><p> The only thing I know is what I don't want. I worked in IT for a big company and it was okay just like staring at ceiling tiles for a hour at the doctor's office is okay. But I was a cost to the business and I felt like a cost. Even if I worked as hard and as consistent as I could it still felt ... okay. I know I don't want to be a cost, I want to be apart of creating the value. </p><p> I don't want to go back to a traditional school. That ship has sailed for me. The Tower on campus feels just as ominous now as it did my first day on campus all those years ago. And while at school I felt like I was prepping for something I wasn't apart of. I'd have to open up some really weird cans of worms to start figuring out why I was so anxious and adrift at school. All I know is that in comparison, I have thrived outside of the traditional school system and I don't want to go through that again.</p><p>So, this feels like when I talk about why I decided to enroll at a coding bootcamp or what it was that made me grab life by the balls and twist but I think that this fire that's burning in me is special and trying to frame it so as to articulate it would be a disservice to it.</p>"	
		}	
	]
	return(allBlogs[postNumber]);
}